# Generated by Django 4.1.7 on 2023-05-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
